# ベースイメージとして Node.js 20 を使用
FROM node:20-alpine

# コンテナ内に作業ディレクトリを作成
WORKDIR /app

# ホストマシンから必要なファイルをコンテナにコピー
# 例: アプリケーションのソースコード、package.json など
COPY ./myapp /app

# アプリケーションの依存関係をインストール
RUN npm install

# アプリケーションがリッスンするポートを指定
EXPOSE 3000

#CMD ["npm", "run", "dev"] # or  CMD ["npm", "start"]
