import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
//import { Toaster } from "@/components/ui/sonner";
//import { toast } from "sonner"
//import Loading from "./loading";
import { Suspense } from "react";
import { useSearchParams } from 'next/navigation';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/*
// エクスポートするページコンポーネント
export default function RootLayout({
  children,
  ...props
}: Readonly<{
  children: React.ReactNode|never;
}>) {
  // ローディングコンポーネント
//  const Loading = () => (
//    <div className="loading-spinner">読み込み中...</div>
//  );

  return (
    <Suspense fallback={ <div className="loading-spinner">読み込み中...</div>}>
      {<></>
      }
    </Suspense>
  );
}
*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode|never;
}>) {
  return (
    <Suspense fallback={ <div className="loading-spinner">読み込み中...</div>}>
      {
        <html lang="en">
          <body
            className={` antialiased`}
          >
            {children ?? <></>}

            {/**
             * TODO
             * 全画面で利用するならば、ここに記述した方が良い
             * テストがてら、zod-login-2に記載してる！！
             * 
             * //import { Toaster } from "@/components/ui/sonner";
             * //import { toast } from "sonner"
             */}
            {/*
            <Toaster richColors />
            */}

          </body>
        </html>
      }
    </Suspense>
  );
}

